MsuTypeNameOverrides:
  "Super Metroid / A Link to the Past Combination Randomizer Legacy": "SMZ3 Classic (Metroid First)"
  "Super Metroid / A Link to the Past Combination Randomizer": "SMZ3 Combo Randomizer"
  "Teenage Mutant Ninja Turtles: Turtles in Time": "TMNT: Turtles in Time"
  "The Legend of Zelda: A Link to the Past": "A Link to the Past"
  "The Legend of Zelda": "Zelda 1 SNES Port"
  "Metroid": "Metroid 1 SNES Port"
Smz3MsuTypes:
  - SMZ3 Classic (Metroid First)
  - SMZ3 Combo Randomizer
MetroidFirstMsuTypes:
  - SMZ3 Classic (Metroid First)
  - Super Metroid
ZeldaFirstMsuTypes:
  - SMZ3 Combo Randomizer
  - A Link to the Past
UserOptionsFilePath: "%LocalAppData%\\MSURandomizer\\msu-user-settings.yml"
MsuCachePath: "%LocalAppData%\\MSURandomizer"
ContinuousReshuffleSeconds: 60
MsuWindowDisplayRandomButton: true
MsuWindowDisplayShuffleButton: true
MsuWindowDisplayContinuousButton: true
MsuWindowDisplayOptionsButton: true
MsuWindowDisplaySelectButton: false
ForcedMsuType:
DisableMessageSender: false
